wordlist:
	edictor wordlist --dataset=../cldf/cldf-metadata.json --name=sabor --addon=borrowed:borrowed,borrowed_score:borrowed_score,borrowed_base:borrowed_base,age:age,age_score:age_score,donor_language:donor_language,donor_value:donor_value
